### PR TITLE
Enhancement drop generics

### PR DESCRIPTION
**Pull request by ppenna**
Description
-------------

This PR fixes https://github.com/demikernel/inetstack/issues/180.

Summary of Changes
------------------------

- Dropped trait bounds on `NetworkRuntime`
- Introduced additional arguments to `Peer`, `Icmpv4Peer`, `TcpPeer`, `UdpPeer` and `ArpPeer` to provide required functionality on each layer of the network stack.

### CODE REVIEW

**Review by anandbonde — APPROVED** [review]
Looks good. The dynamic dispatch for PacketBuf causes the use of Box::new. This was unclear to me at first glance, but it became clear after looking at the relevant changes to the runtime (transmit()) function. Also confirmed this in discussion with Pedro.

**Comment by BrianZill** [comment]
> Looks good. The dynamic dispatch for PacketBuf causes the use of Box::new. This was unclear to me at first glance, but it became clear after looking at the relevant changes to the runtime (transmit()) function. Also confirmed this in discussion with Pedro.

Yes.  I also discussed this with Pedro.  We need to fix this somehow, either by using a different form of polymorphism for PacketBuf (like an enum), or by replacing PacketBuf with a fixed type.

**Comment by BrianZill** [comment]
Another thing this change exposed was all of the cross-layer violations that were being hidden by the old runtime generic.  Some of this can be fixed by having a proper network interface (NIC) abstraction and/or a real IP layer.

**Review by BrianZill — APPROVED** [review]
This all looks good.

But we'll need to fix the PacketBuf dynamic dispatch issue.  I've opened inetstack Issue #194 for this.  Should we have a corresponding issue on the runtime repo?  Or should it only be there?

I've also opened Issue #195 for the "we only support 1 IP address and 1 MAC address" problem that this PR makes painfully obvious.

**Comment by ppenna** [comment]
> This all looks good.
> 
> But we'll need to fix the PacketBuf dynamic dispatch issue. I've opened inetstack Issue #194 for this. Should we have a corresponding issue on the runtime repo? Or should it only be there?
> 
> I've also opened Issue #195 for the "we only support 1 IP address and 1 MAC address" problem that this PR makes painfully obvious.

@BrianZill I've transferred the issue to the runtime repo, since it affects all Network LibOSes. I'm curious to ask if you have any solution for this issue, top of mind.

**Pull request merged**
